apiVersion: v1
kind: Service
metadata:
  name: vcard-service
  labels:
    app: vcard
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: vcard